### ISSUE TITLE
Global Event filterObjectEnterContainer -- Does not fire for chip stacks

### ISSUE THREAD

**Issue by bobbybuntin** [Berserk-Games/Tabletop-Simulator-API#56]
Not sure if this is a bug or a feature request, but the filterObjectEnterContainer event does not fire for chip stacks.   This seems to be the only container event not fired on chip stacks.   

That would be an enhancement (or bug fix) that I would like to see.

Apologies if there is a better place I should have posted this.  I'm happy to repost elsewhere if someone has another suggestion.

**Comment by AufderWelt** [comment]
good question, if i look at the api, im not sure, if chips stacks are considered as containers...

**Comment by TheDorit0** [comment]
I think it may actually fire in the global script, but not if you put the filter function in the script of another object (even if there is no function in the global script).  The other enterContainer functions can still be triggered this way, just not filter.

Since posting this, I actually moved away from using standard chips in my game, so I can't confirm for certain as I write this that the standard chips act this way, but that seems to be the way it acts for custom chips.   I got around this by just putting a filter function in the global script and then calling my other object script from that global function.

**Comment by nabbydude** [comment]
Looks like your issue pertains to Tabletop Simulator itself, and not the API documentation, which this repo is for. Check out [https://tabletopsimulator.nolt.io/](https://tabletopsimulator.nolt.io/) to submit and vote for bugs, suggestions, and requests for the game itself. If you just have a question about the game, also check out [The Official Tabletop Simulator Discord Server](https://discord.com/invite/tabletopsimulator), the community may be able to answer it.
